name: Issues
on:
  issues:
    types: opened
jobs:
  issue_information:
    runs-on: ubuntu-latest
    steps:
      - name: Display Issue Information
        run: "echo Issue: ${{ github.event.issue }}"
